name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t hello-world-nginx:v1 . # building docker image with tag

    - name: Run Docker container
      run: docker run -d -p 8080:80 --name my-nginx-container hello-world-nginx:v1 # runnign and mapping correct port for image

    - name: Declare the sha_short and branch
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

    - name: check branch and commit-sha
      run: |
      echo "Branch: ${{ env.branch }}"
      echo "Sha: ${{ env.sha_short }}"

    - name: Verify Nginx is running (Optional - for small demonstration)
      run: |
        sleep 5 # Give Nginx a moment to start
        curl http://localhost:8080 # trying to access Nginx on the mapped port
      shell: bash

    - name: Clean up Docker container (Optional - good practice)
      if: always() # this step will now always run and remove container (even if previous steps failed)
      run: docker rm -f my-nginx-container # removing the container forcefully
    