name: Deploy Nginx App with Helm

on:
  push:
    branches: [ "main", "01_DockerTest" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted # make sure docker and helm are installed
    permissions:
      contents: read
      packages: write # need for pushing container registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # docker image building and pushing
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define Image Repository
        id: image_repo
        run: |
          echo "IMAGE_REPO=daymonp/hello-world-nginx" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # --- THIS IS THE CRITICAL CHANGE YOU NEED TO MAKE ---
          # Replace the 'tags: |' block with the following:
          tags:
            - ${{ steps.image_repo.outputs.IMAGE_REPO }}:latest
            - ${{ steps.image_repo.outputs.IMAGE_REPO }}:${{ github.sha }}
          # ---------------------------------------------------

      # kubernetes helm deployement
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create Kubernetes Namespace (if it doesn't exist)
        run: |
          kubectl get namespace default || kubectl create namespace default

      - name: Install/Upgrade Helm Chart
        run: |
          helm upgrade --install my-hello-nginx ./my-nginx-chart \
            --namespace default \
            --set image.repository=${{ steps.image_repo.outputs.IMAGE_REPO }} \
            --set image.tag=${{ github.sha }} \
            --atomic \
            --wait
        env:
          DOCKER_IMAGE_REPO: ${{ steps.image_repo.outputs.IMAGE_REPO }}
          DOCKER_IMAGE_TAG: ${{ github.sha }}

      - name: Test the final result (Optional - for validation)
        run: |
          echo "Deployment initiated. Waiting for Pods to be ready..."
          kubectl get pods -n default -l app.kubernetes.io/instance=my-hello-nginx --field-selector=status.phase=Running --timeout=120s
          echo "Pods are running. Attempting to get pod name and check logs..."

          # get the pod name - using 'Select-Object -First 1' for robustness in case multiple pods
          $POD_NAME = (kubectl get pods -n default -l app.kubernetes.io/instance=my-hello-nginx -o jsonpath='{.items[0].metadata.name}')
          echo "Pod name: $POD_NAME"

          echo "Checking Nginx logs for a successful request..."
          kubectl logs $POD_NAME -n default | Select-String "GET / "
          if ($LASTEXITCODE -eq 0) {
            echo "Nginx served content as expected based on logs!"
          } else {
            echo "Nginx log check failed or 'GET / ' entry not found."
            exit 1
          }